# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            JieYing Peng
tagline:          'blog'
description:      'My Journey from Accountant to Front-End Developer.'
url:              http://lala010addict.github.io
baseurl:          
commentsystem:    disqus
disqus:           jieyingpeng

author:
  name:           JieYing Peng
  url:            https://jieyingpeng.ghost.io/

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:


  - icon:         github
    url:          https://github.com/lala010addict
    desc:         Fork me on github

  - icon:        instagram
    url:          https://instagram.com/lalalala010/
    desc:         

      - icon:        linkedin
    url:          https://www.linkedin.com/in/jieyingpeng

      - icon:         twitter
    url:          https://twitter.com/bunnynporkbelly
    desc:         Follow me on twitter

      - icon:     mail
    url:          jieyingpeng010@gmail.com


  - icon:         feed
    url:          http://lala010addict.github.io/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:        JieYing Peng
  url:            http://lala010addict.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
